language: node_js
node_js:
  - "7"
  - "6"

before_install:
  - npm install -g @angular/cli

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:prod; else npm run build; fi;

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  fqdn: metabmaster.jcbwndsr.com
  project_name: MetabMaster
  local_dir: dist
