language: node_js
node_js:
  - "7"
  - "6"

before_install:
  - npm install -g @angular/cli

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build:prod; else npm run build; fi;

deploy:
  provider: surge
  project: ./dist/
  domain: metabmaster.surge.sh
  skip_cleanup: true
  on:
    branch: master
