language: node_js
node_js:
  - "7"
  - "6"

before_install:
  - npm install -g @angular/cli

script:
  - npm run build

deploy:
  provide: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  fqdn: metabmaster.jcbwndsr.com
  project_name: MetabMaster
  local_dir: dist
